project:
  type: manuscript
  output-dir: docs
  post-render: deploy.R

execute:
  freeze: auto
  cache: false

manuscript:
  article: index.qmd
  notebooks:
    - notebook: analysis.qmd
      title: "Analysis Notebook"

format:
  html:
    theme: cosmo
    format-links: [pdf, docx]
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    link-citations: true
    includes:
      in-header: references/header.tex
  docx:
    reference-doc: references/reference.docx

bibliography: references/references.bib
csl: references/apa.csl
